version: "3"

services:
  app:
    build: .
    env_file:
      - ./app/.env
    ports:
      - "5001:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
    restart: always
